esp_jpeg: Added example
espressif/idf-extra-components pull request #198
Opened 2023-07-04 08:17 UTC by espzav

# Checklist

- [ ] Component contains License
- [ ] Component contains README.md
- [ ] Component contains idf_component.yml file with `url` field defined
- [ ] Component was added to [upload job](https://github.com/espressif/idf-extra-components/blob/master/.github/workflows/upload_component.yml#L18)
- [ ] Component was added to [build job](https://github.com/espressif/idf-extra-components/blob/master/test_app/CMakeLists.txt#L8)
- [ ] _Optional:_ Component contains unit tests
- [ ] CI passing

# Change description
Moved tjpgd example from IDF to this component and used BSP for LCD initialization.

2023-07-04 09:46 UTC, suda-morris requested changes
LGTM, left some small comments

2023-07-04 09:46 UTC, suda-morris commented on esp_jpeg/examples/tjpgd/main/pretty_effect.h
> +
missing cpp guard

2023-07-04 09:46 UTC, suda-morris commented on esp_jpeg/examples/tjpgd/main/pretty_effect.c
> +#include "sdkconfig.h"
no CONFIG_xxx macro found in this file, maybe we can remove this header file

2023-07-04 09:46 UTC, suda-morris commented on esp_jpeg/examples/tjpgd/main/lcd_tjpgd_example_main.c
> +//#include "esp_lcd_panel_vendor.h"
shall we remove them?

2023-07-04 09:46 UTC, suda-morris commented on esp_jpeg/examples/tjpgd/main/idf_component.yml
> +  esp_jpeg: ">=1.0.2"
shall we add "override_path" for it?

2023-07-04 09:46 UTC, suda-morris commented on esp_jpeg/examples/tjpgd/main/decode_image.h
> +
missing cpp guard in this file

2023-07-04 09:46 UTC, suda-morris commented on esp_jpeg/examples/tjpgd/main/decode_image.c
> +#include "freertos/FreeRTOS.h"
```suggestion
#include <string.h>
#include "decode_image.h"
#include "jpeg_decoder.h"
#include "esp_log.h"
#include "esp_check.h"
#include "freertos/FreeRTOS.h"
```

2023-07-04 10:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/idf-extra-components?pullRequest=198) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/idf-extra-components?pullRequest=198) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/idf-extra-components?pullRequest=198) it.</sub>

2023-07-04 10:55 UTC, espzav commented
@suda-morris Thank you for review.
note: The BSP is nto supported with IDF4.4 and lower. We will add support for IDF4.4 in future. Should I wait with this for support IDF4.4 or change IDF compatibility to `>=5.0`?

2023-07-05 02:30 UTC, suda-morris commented
> @suda-morris Thank you for review. note: The BSP is nto supported with IDF4.4 and lower. We will add support for IDF4.4 in future. Should I wait with this for support IDF4.4 or change IDF compatibility to `>=5.0`?

No, we don't have to wait for that because this example's focus is not on the BSP, any working BSP, any version can do.

2023-07-10 07:37 UTC, espzav commented
@suda-morris @tore-espressif Please, how can I disable tests for this example for IDF < 5.0 ?

2023-07-11 07:14 UTC, espzav commented
@suda-morris please, is it ok now? Can we merge it after tests will pass?

2023-07-13 08:09 UTC, suda-morris commented on esp_jpeg/examples/tjpgd/main/Kconfig.projbuild
> +    config EXAMPLE_LCD_SPI_8_LINE_MODE
shall we remove this since the BSP driver doesn't contain any LCD utilizes the SPI octal bus.

2023-07-13 08:54 UTC, merged